### PR TITLE
feat: allow single tap selection on mobile devices

### LINKED ISSUE #166: Double tap required on mobile devices
When selecting an emoji from the picker on a touch screen device (I tried it on iPhone SE & iPad), two taps are required to trigger the `emojiSelect` and/or `emojiClick` events and close the picker.
That behavior might well be intended! (Otherwise, if `[showPreview]="true"` is set it would be impossible to see said preview.)

However - when setting `[showPreview]="true"` it would be useful to have it react to a single tap. Therefore I suggest adding a new boolean Input (e.g. `emitOnTouch`) that causes this behavior.

### PR DESCRIPTION
**Pull request by floAtEbcont**
This is would be one possibility to solve #166 

closes #166

### CODE REVIEW

**Comment by floAtEbcont** [comment]
@scttcper Thank you so much for merging this PR so quickly! :-)

Unfortunately I found an issue with my addition that I have previously overlooked:
The event is also triggered when the user tries to swipe the emoji list. This can be easily bypassed by adding the following to the component using emoji-mart:

```typescript
        @HostListener('body:touchmove', ['$event']) touchmove(event) {
		this.dragging = true;
	}

	@HostListener('body:touchstart', ['$event']) touchstart(event) {
		this.dragging = false;
        }
```
... and then setting the new property like this: `[emitOnTouch]="!dragging"`. This will not be apparent to other users though, so this logic should maybe be added to the emoji-mart.

However, this might not be the best approach at all: The `touchend` event is always triggered with a delay. So I started researching why the click event's not happening in the first place, and found this rule disables it:

```
The target element, or any of its ancestors up to but not including the <body>, has an explicit event handler set for any of the mouse events. This event handler may be an empty function.
``` 
(s. https://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html - Safari's oddities)

So in [my fork](https://github.com/floAtEbcont/ngx-emoji-mart/commit/e2ee7c888ae3b388f5f6db5937293bd85f533135#diff-0bd3a02919a4b793c9532eac31f21e95R92) I just made adding the mouse hover events depend on `[showPreview]="true"`. This works fine in the demo app, but for some reason not in the app I'm using emoji-mart for. I haven't yet figured out why, so I haven't created another PR yet.

Sorry for this, I really should have done more testing.

**Comment by scttcper** [comment]
@floAtEbcont 	can you make a pr if you get a chance?

**Comment by scttcper** [comment]
@floAtEbcont forgot to respond. But all the styles are taken from the react project this is based on.

**Pull request merged**
